"""
src/behavior/mappe/mappa_patologie.py
──────────────────────────────────────
Mapping codici MCM (1-523) → nome patologia
+ normalizzazione Q7a (Area Terapeutica)
+ helper di decodifica Q7b
"""

# ──────────────────────────────────────────────────────
# 523 codici MCM → patologia
# ──────────────────────────────────────────────────────
CODICI_PATOLOGIE: dict[int, str] = {
    1: "Malattie infettive intestinali",
    2: "Altra ernia della cavità addominale",
    3: "Tubercolosi",
    4: "Ernia inguinale",
    5: "Malattie batteriche trasmesse da animali",
    6: "Appendicite acuta",
    7: "Altre malattie batteriche",
    8: "Altri disturbi dello stomaco e del duodeno",
    9: "Infezioni da virus dell'immunodeficienza umana (HIV)",
    10: "Disturbi della funzione gastrica",
    11: "Poliomielite ed altre malattie virali del sistema nervoso centrale",
    12: "Gastrite e duodenite",
    13: "Malattie virali con esantema",
    14: "Ulcera gastrodigiunale",
    15: "Malattie virali da artropodi",
    16: "Ulcera peptica, sito non specificato",
    17: "Altre malattie da virus e clamidia",
    18: "Ulcera duodenale",
    19: "Rickettsiosi ed altre malattie trasmesse da artropodi",
    20: "Ulcera gastrica",
    21: "Sifilide ed altre malattie veneree",
    22: "Malattie dell'esofago",
    23: "Altre malattie da spirochete",
    24: "Ernie della cavità addominale",
    25: "Micosi",
    26: "Malattie dell'esofago, stomaco e duodeno",
    27: "Elmintiasi",
    28: "Malattie della cavità orale, delle ghiandole salivari e delle mascelle",
    29: "Altre malattie infettive e parassitarie",
    30: "Appendicite",
    31: "Postumi di malattie infettive e parassitarie",
    32: "Enteriti e coliti non infettive",
    33: "Altre malattie dell'intestino e del peritoneo",
    34: "Altre malattie dell'apparato digerente",
    35: "Insufficienza vascolare dell'intestino",
    36: "Colite ulcerosa",
    37: "Enterite regionale",
    38: "Altro",
    39: "Carenza congenita del fattore XI",
    40: "Disturbi congeniti del fattore IX",
    41: "Carenza congenita di altri fattori della coagulazione",
    42: "Disturbi congeniti del fattore VIII",
    43: "Malattia di von Willebrand",
    44: "Anemia aplastica",
    45: "Disturbo emorragico da anticoagulanti circolanti",
    46: "Anemia emolitica acquisita",
    47: "Sindrome da defibrinazione",
    48: "Anemie emolitiche ereditarie",
    49: "Carenza acquisita di fattori della coagulazione",
    50: "Altre anemie da carenza",
    51: "Altri e non specificati difetti della coagulazione",
    52: "Anemie da carenza di ferro",
    53: "Altre e non specificate anemie",
    54: "Difetti della coagulazione",
    55: "Porpora ed altre condizioni emorragiche",
    56: "Malattie dei globuli bianchi",
    57: "Altre malattie del sangue e degli organi emopoietici",
    58: "Altro",
    59: "Reumatismo articolare acuto",
    60: "Malattie delle vene e dei vasi linfatici ed altre malattie del sistema circolatorio",
    61: "Cardiopatie reumatiche croniche",
    62: "Malattie delle arterie, arteriole e capillari",
    63: "Ipertensione arteriosa",
    64: "Malattie cerebrovascolari",
    65: "Malattie ischemiche del cuore",
    66: "Altre malattie del cuore",
    67: "Malattie del circolo polmonare",
    68: "Infarto miocardico acuto",
    69: "Altre forme acute e subacute di cardiopatia ischemica",
    70: "Angina pectoris",
    71: "Occlusione e stenosi delle arterie precerebrali",
    72: "Ischemia cerebrale transitoria",
    73: "Occlusione delle arterie cerebrali",
    74: "Altro",
    75: "Foruncolo e favo",
    76: "Dermatosi eritemato-desquamative",
    77: "Flemmone e ascesso delle dita",
    78: "Dermatite atopica e affezioni correlate",
    79: "Altri flemmoni e ascessi",
    80: "Dermatite da contatto ed altri eczemi",
    81: "Linfadenite acuta",
    82: "Dermatiti da sostanze assunte per via sistemica",
    83: "Impetigine",
    84: "Dermatosi bollose",
    85: "Cisti pilonidale",
    86: "Affezioni eritematose",
    87: "Altre infezioni localizzate della cute e del tessuto sottocutaneo",
    88: "Psoriasi e affezioni similari",
    89: "Lichen",
    90: "Prurito e affezioni correlate",
    91: "Calli e callosità",
    92: "Altre affezioni atrofiche e ipertrofiche della cute",
    93: "Altre dermatosi",
    94: "Malattie delle unghie",
    95: "Altre alterazioni della cute e del tessuto sottocutaneo",
    96: "Orticaria",
    97: "Ulcerazione cronica della cute",
    98: "Malattie delle ghiandole sebacee",
    99: "Malattie dei peli e dei follicoli piliferi",
    100: "Malattie delle ghiandole sudoripare",
    101: "Ustioni",
    102: "Altro",
    103: "Nefrite, sindrome nefrosica e nefrosi",
    104: "Altre patologie della prostata",
    105: "Altre patologie del sistema urinario",
    106: "Patologie infiammatorie della prostata",
    107: "Patologie degli organi genitali maschili",
    108: "Idrocele",
    109: "Disturbi del seno",
    110: "Orchite ed epididimite",
    111: "Malattie infiammatorie degli organi pelvici femminili",
    112: "Prepuzio esuberante e fimosi",
    113: "Altre malattie dall'apparato genitale femminile",
    114: "Iperplasia della prostata",
    115: "Infertilità maschile",
    116: "Malattie infiammatorie dell'ovaio, delle tube e del peritoneo",
    117: "Malattia infiammatoria della cervice, della vagina e della vulva",
    118: "Malattie infiammatorie dell'utero, esclusa la cervice",
    119: "Displasia benigna della mammella",
    120: "Altri disturbi del seno",
    121: "Infezioni del rene",
    122: "Altre patologie dell'uretra e del sistema urinario",
    123: "Stenosi uretrale",
    124: "Uretrite non trasmessa sessualmente e sindrome uretrale",
    125: "Calcolosi renale ed ureterale",
    126: "Altre patologie della vescica",
    127: "Altre patologie del rene e dell'uretere",
    128: "Cistite",
    129: "Calcolo del tratto urinario inferiore",
    130: "Altro",
    131: "Deficienze nutrizionali",
    132: "Disturbi della ghiandola tiroidea",
    133: "Altri disturbi metabolici ed immunitari",
    134: "Disturbi di altre ghiandole endocrine",
    135: "Altro",
    136: "Specificare la patologia",
    137: "Tumori maligni delle labbra, della cavità orale, della faringe",
    138: "Tumori maligni di altre e non specificate sedi",
    139: "Tumori maligni dell'apparato digerente e del peritoneo",
    140: "Carcinomi in situ",
    141: "Tumori maligni dell'apparato respiratorio e degli organi intratoracici",
    142: "Tumori benigni",
    143: "Tumori maligni delle ossa, del tessuto connettivo, della cute e della mammella",
    144: "Tumori maligni degli organi genitourinari",
    145: "Tumori maligni del tessuto linfatico ed emopoietico",
    146: "Tumori di comportamento incerto",
    147: "Tumori di natura non specificata",
    148: "Tumori maligni delle labbra",
    149: "Tumori maligni della lingua",
    150: "Tumori maligni delle ghiandole salivari maggiori",
    151: "Tumori maligni della ghiandola parotide",
    152: "Tumori maligni delle ghiandole",
    153: "Tumori maligni delle gengive",
    154: "Tumori maligni del pavimento della bocca",
    155: "Tumori maligni del palato",
    156: "Tumori maligni dell'orofaringe",
    157: "Tumori maligni della tonsilla",
    158: "Tumori maligni della fossa tonsillare",
    159: "Tumori maligni dei pilastri tonsillari",
    160: "Tumori maligni della vallecula",
    161: "Tumori maligni della faccia anteriore dell'epiglottide",
    162: "Tumori maligni del rinofaringe",
    163: "Tumori maligni dell'ipofaringe",
    164: "Tumori maligni dell'esofago",
    165: "Tumori maligni dello stomaco",
    166: "Tumori maligni del cardias",
    167: "Tumori maligni del piloro",
    168: "Tumori maligni dell'intestino tenue",
    169: "Tumori maligni del duodeno",
    170: "Tumori maligni del digiuno",
    171: "Tumori maligni dell'ileo",
    172: "Tumori maligni del diverticolo di Meckel",
    173: "Tumori maligni del colon",
    174: "Tumori maligni del flessura epatica",
    175: "Tumori maligni del colon trasverso",
    176: "Tumori maligni del colon discendente",
    177: "Tumori maligni del sigma",
    178: "Tumori maligni del ceco",
    179: "Tumori maligni dell'appendice",
    180: "Tumori maligni del colon ascendente",
    181: "Tumori maligni della flessura splenica",
    182: "Tumori maligni del retto",
    183: "Tumori maligni del canale anale",
    184: "Tumori maligni dell'ano",
    185: "Altri tumori maligni del retto, della giunzione rettosigmoidea e dell'ano",
    186: "Tumori maligni del fegato e dei dotti biliari intraepatici",
    187: "Tumori maligni primitivi del fegato",
    188: "Tumori maligni dei dotti biliari intraepatici",
    189: "Tumori maligni del fegato, non specificato",
    190: "Tumori maligni della colecisti",
    191: "Tumori maligni del pancreas",
    192: "Tumori maligni del retroperitoneo e del peritoneo",
    193: "Tumori maligni delle cavità nasali, dell'orecchio medio e dei seni paranasali",
    194: "Tumori maligni di tuba uditiva, orecchio medio e cellule mastoidee",
    195: "Tumori maligni della laringe",
    196: "Tumori maligni della glottide",
    197: "Tumori maligni delle cartilagini laringee",
    198: "Tumori maligni della trachea, dei bronchi e dei polmoni",
    199: "Tumori maligni della pleura",
    200: "Tumori maligni del timo, del cuore e del mediastino",
    201: "Tumori maligni delle ossa e delle cartilagini articolari",
    202: "Tumori maligni del connettivo e di altri tessuti molli",
    203: "Tumori maligni del torace",
    204: "Tumori maligni dell'addome",
    205: "Tumori maligni della pelvi",
    206: "Tumori maligni del tronco",
    207: "Tumori maligni di altre sedi specificate del connettivo",
    208: "Tumori maligni di connettivo e altri tessuti molli, sede non specificata",
    209: "Melanoma maligno della cute",
    210: "Melanoma maligno delle labbra",
    211: "Melanoma maligno della palpebra",
    212: "Melanoma maligno di orecchio e condotto uditivo esterno",
    213: "Melanoma maligno di cuoio capelluto e collo",
    214: "Melanoma maligno del tronco",
    215: "Melanoma cutaneo, sede non specificata",
    216: "Altri tumori maligni della cute",
    217: "Altri tumori maligni della cute delle labbra",
    218: "Altri tumori maligni della cute della palpebra",
    219: "Altri tumori maligni della cute dell'orecchio",
    220: "Altri tumori maligni della cute della faccia",
    221: "Altri tumori maligni del cuoio capelluto e collo",
    222: "Altri tumori maligni della cute del tronco",
    223: "Altri tumori maligni della cute dell'arto superiore",
    224: "Altri tumori maligni della cute dell'arto inferiore",
    225: "Altri tumori maligni di altre sedi specificate della cute",
    226: "Altri tumori maligni della cute, sede non specificata",
    227: "Tumori maligni della mammella della donna",
    228: "Tumori maligni della mammella dell'uomo",
    229: "Tumori maligni di capezzolo e areola della mammella dell'uomo",
    230: "Tumori maligni di altre e non specificate sedi della mammella dell'uomo",
    231: "Sarcoma di Kaposi",
    232: "Tumori maligni dell'utero, parte non specificata",
    233: "Tumori maligni del collo dell'utero (cervice uterina)",
    234: "Tumori maligni dell'endocervice",
    235: "Tumori maligni dell'esocervice",
    236: "Tumori maligni di altre sedi specificate della cervice",
    237: "Tumori maligni della cervice uterina, non specificata",
    238: "Tumori maligni della placenta",
    239: "Tumori maligni del corpo dell'utero",
    240: "Tumori maligni del corpo dell'utero, eccetto l'istmo",
    241: "Tumori maligni dell'istmo",
    242: "Tumori maligni di altre specificate sedi del corpo dell'utero",
    243: "Tumori maligni dell'ovaio e degli altri annessi uterini",
    244: "Tumori maligni dell'ovaio",
    245: "Tumori maligni della tuba di Falloppio",
    246: "Tumori maligni del legamento largo",
    247: "Tumori maligni del parametrio",
    248: "Tumori maligni del legamento rotondo",
    249: "Tumori maligni di altre sedi specificate degli annessi uterini",
    250: "Tumori maligni degli annessi uterini, non specificati",
    251: "Tumori maligni di altri e non specificati organi genitali femminili",
    252: "Tumori maligni della vagina",
    253: "Tumori maligni delle grandi labbra",
    254: "Tumori maligni delle piccole labbra",
    255: "Tumori maligni della clitoride",
    256: "Tumori maligni della vulva, non specificata",
    257: "Tumori maligni di altre specificate sedi degli organi genitali femminili",
    258: "Tumori maligni degli organi genitali femminili, sede non specificata",
    259: "Tumori maligni della prostata",
    260: "Tumori maligni del testicolo",
    261: "Tumori maligni del testicolo ritenuto",
    262: "Tumori maligni del testicolo: altro e non specificato",
    263: "Tumori maligni del pene e degli altri organi genitali maschili",
    264: "Tumori maligni del prepuzio",
    265: "Tumori maligni del glande",
    266: "Tumori maligni del corpo del pene",
    267: "Tumori maligni del pene, parte non specificata",
    268: "Tumori maligni dell'epididimo",
    269: "Tumori maligni del funicolo spermatico",
    270: "Tumori maligni dello scroto",
    271: "Tumori maligni di altre specificate sedi degli organi genitali maschili",
    272: "Tumori maligni degli organi genitali maschili, sede non specificata",
    273: "Tumori maligni della vescica",
    274: "Tumori maligni del trigono vescicale",
    275: "Tumori maligni della cupola vescicale",
    276: "Tumori maligni della parete laterale della vescica",
    277: "Tumori maligni della parete anteriore della vescica",
    278: "Tumori maligni della parete posteriore della vescica",
    279: "Tumori maligni del collo vescicale",
    280: "Tumori maligni dell'ostio ureterale",
    281: "Tumori maligni dell'uraco",
    282: "Tumori maligni di altre specificate sedi della vescica",
    283: "Tumori maligni di parte non specificata della vescica",
    284: "Tumori maligni del rene e di altri organi urinari",
    285: "Tumori maligni del rene, eccetto la pelvi",
    286: "Tumori maligni della pelvi renale",
    287: "Tumori maligni dell'uretere",
    288: "Tumori maligni dell'uretra",
    289: "Tumori maligni delle ghiandole parauretrali",
    290: "Tumori maligni di altre specificate sedi degli organi urinari",
    291: "Tumori maligni degli organi urinari, sede non specificata",
    292: "Tumori maligni dell'occhio",
    293: "Tumori maligni del bulbo oculare",
    294: "Tumori maligni dell'orbita",
    295: "Tumori maligni della ghiandola lacrimale",
    296: "Tumori maligni della congiuntiva",
    297: "Tumori maligni della cornea",
    298: "Tumori maligni della retina",
    299: "Tumori maligni della coroide",
    300: "Tumori maligni dei condotti lacrimali",
    301: "Tumori maligni di altre specificate sedi dell'occhio",
    302: "Tumori maligni dell'occhio, parte non specificata",
    303: "Tumori maligni dell'encefalo",
    304: "Tumori maligni del cervello, eccetto lobi e ventricoli",
    305: "Tumori maligni del lobo frontale",
    306: "Tumori maligni del lobo temporale",
    307: "Tumori maligni del lobo parietale",
    308: "Tumori maligni del lobo occipitale",
    309: "Tumori maligni dei ventricoli",
    310: "Tumori maligni del cervelletto",
    311: "Tumori maligni del tronco dell'encefalo",
    312: "Tumori maligni di altre parti dell'encefalo",
    313: "Tumori maligni dell'encefalo, non specificato",
    314: "Tumori maligni di altre e non specificate parti del sistema nervoso",
    315: "Tumori maligni dei nervi cranici",
    316: "Tumori maligni delle meningi cerebrali",
    317: "Tumori maligni del midollo spinale",
    318: "Tumori maligni delle meningi spinali",
    319: "Tumori maligni di altre sedi specificate del sistema nervoso",
    320: "Tumori maligni del sistema nervoso, parte non specificata",
    321: "Tumori maligni della ghiandola tiroide",
    322: "Tumori maligni delle altre ghiandole endocrine",
    323: "Tumori maligni delle ghiandole surrenali",
    324: "Tumori maligni delle ghiandole paratiroidi",
    325: "Tumori maligni dell'ipofisi",
    326: "Tumori maligni della ghiandola pineale",
    327: "Tumori maligni del glomo carotideo",
    328: "Tumori maligni del glomo aortico e altri paragangli",
    329: "Tumori maligni delle ghiandole endocrine, sede non specificata",
    330: "Tumori maligni di altre e mal definite sedi",
    331: "Tumori maligni di testa, faccia e collo",
    332: "Tumori maligni del torace",
    333: "Tumori maligni dell'addome",
    334: "Tumori maligni della pelvi",
    335: "Tumori maligni dell'arto superiore",
    336: "Tumori maligni dell'arto inferiore",
    337: "Tumori maligni di altre sedi specificate",
    338: "Tumori maligni secondari e non specificati dei linfonodi",
    339: "Tumori maligni secondari e non specificati",
    340: "Tumori maligni disseminati",
    341: "Mieloma multiplo e neoplasie immunoproliferative",
    342: "Leucemia plasmacellulare",
    343: "Altre neoplasie immunoproliferative",
    344: "Leucemia linfoide",
    345: "Leucemia linfoide acuta",
    346: "Leucemia linfoide cronica",
    347: "Leucemia linfoide subacuta",
    348: "Altre leucemie linfatiche",
    349: "Leucemia mieloide",
    350: "Leucemia mieloide acuta",
    351: "Leucemia mieloide cronica",
    352: "Leucemia mieloide subacuta",
    353: "Sarcoma mieloide",
    354: "Sarcoma mieloide, senza menzione di remissione",
    355: "Sarcoma mieloide, in remissione",
    356: "Leucemia monocitica",
    357: "Leucemia monocitica acuta",
    358: "Leucemia monocitica acuta, senza menzione di remissione",
    359: "Leucemia monocitica acuta, in remissione",
    360: "Leucemia monocitica cronica",
    361: "Leucemia monocitica cronica, senza menzione di remissione",
    362: "Leucemia monocitica cronica, in remissione",
    363: "Leucemia monocitica subacuta",
    364: "Leucemia monocitica subacuta, senza menzione di remissione",
    365: "Leucemia monocitica subacuta, in remissione",
    366: "Altre leucemie monocitiche",
    367: "Altre leucemie monocitiche, senza menzione di remissione",
    368: "Altre leucemie monocitiche, in remissione",
    369: "Leucemia monocitica, non specificata",
    370: "Leucemia monocitica, non specificata, senza menzione di remissione",
    371: "Leucemia monocitica, non specificata, in remissione",
    372: "Altre leucemie",
    373: "Altro",
    374: "Artropatie e disturbi correlati",
    375: "Artropatia associata ad altri disturbi",
    376: "Dorsopatie",
    377: "Artropatie da microcristalli",
    378: "Reumatismo, escluse le forme dorsali",
    379: "Artropatie da agenti infettivi",
    380: "Osteopatie, condropatie e deformità acquisite",
    381: "Malattie diffuse del tessuto connettivo",
    382: "Artrite reumatoide ed altre poliartropatie infiammatorie",
    383: "Altre artropatie non specificate",
    384: "Artrosi",
    385: "Lesioni interne del ginocchio",
    386: "Altre e non specificate patologie articolari",
    387: "Altre lesioni articolari",
    388: "Capsulite adesiva scapolo-omerale",
    389: "Entesopatia non specificata",
    390: "Sindrome della cuffia dei rotatori",
    391: "Altre entesopatie periferiche",
    392: "Altre affezioni della regione della spalla",
    393: "Entesopatia della caviglia e del tarso",
    394: "Entesopatia della regione del gomito",
    395: "Entesopatia del ginocchio",
    396: "Entesopatia del polso e del carpo",
    397: "Entesopatia della regione dell'anca",
    398: "Miosite infettiva",
    399: "Disturbi non specificati di muscoli, legamenti e fasce",
    400: "Calcificazione e ossificazione muscolari",
    401: "Altri disturbi dei muscoli, dei legamenti e delle fasce",
    402: "Altri specifici disturbi muscolari",
    403: "Altre fibromatosi di muscoli, legamenti e fasce",
    404: "Morbo di Dupuytren",
    405: "Osteomielite, periostite e altre infezioni ossee",
    406: "Lesioni non allopatiche",
    407: "Osteite deformante e osteopatie associate",
    408: "Altre deformazioni acquisite dell'apparato muscoloscheletrico",
    409: "Osteocondropatie",
    410: "Deviazioni della colonna vertebrale",
    411: "Altri disturbi delle ossa e delle cartilagini",
    412: "Altre deformazioni acquisite degli arti",
    413: "Piede piatto",
    414: "Deformazioni acquisite delle dita del piede",
    415: "Frattura",
    416: "Fratture del collo e del tronco",
    417: "Lussazioni",
    418: "Distorsioni e distrazioni delle articolazioni",
    419: "Fratture degli arti superiori",
    420: "Traumatismi interni del torace, dell'addome e della pelvi",
    421: "Fratture degli arti inferiori",
    422: "Altro",
    423: "Disturbi nevrotici",
    424: "Stati psicotici organici",
    425: "Disturbi di personalità",
    426: "Altre psicosi",
    427: "Deviazioni e disturbi sessuali",
    428: "Disturbi nevrotici della personalità e altri disturbi psichici",
    429: "Sindrome di dipendenza da alcool",
    430: "Ritardo mentale",
    431: "Dipendenza da droghe",
    432: "Meningite batterica",
    433: "Abuso di droghe senza dipendenza",
    434: "Meningite da altri microrganismi",
    435: "Disfunzioni fisiche originate da fattori psichici",
    436: "Meningite da causa non specificata",
    437: "Sintomi o sindromi speciali non classificati altrove",
    438: "Encefalite, mielite ed encefalomielite",
    439: "Reazione acuta allo stress",
    440: "Ascesso intracranico ed intrarachideo",
    441: "Reazione di adattamento",
    442: "Degenerazioni cerebrali",
    443: "Disturbi psichici specifici non psicotici da danno cerebrale organico",
    444: "Altre degenerazioni cerebrali",
    445: "Disturbo depressivo",
    446: "Morbo di Parkinson",
    447: "Disturbi della condotta",
    448: "Altre malattie extrapiramidali e disturbi del movimento",
    449: "Disturbo delle emozioni specifico dell'infanzia e dell'adolescenza",
    450: "Malattie spinocerebellari",
    451: "Sindrome ipercinetica dell'infanzia",
    452: "Malattie delle cellule delle corna anteriori",
    453: "Ritardi specifici dello sviluppo",
    454: "Altre malattie del midollo spinale",
    455: "Disturbi del sistema nervoso autonomo",
    456: "Sclerosi multipla",
    457: "Altre malattie demielinizzanti del sistema nervoso centrale",
    458: "Altri e non specificati disturbi del sistema nervoso",
    459: "Altre condizioni morbose dell'encefalo",
    460: "Emiplegia e emiparesi",
    461: "Cataplessia e narcolessia",
    462: "Paralisi cerebrale infantile",
    463: "Emicrania",
    464: "Altre sindromi paralitiche",
    465: "Epilessie",
    466: "Altro",
    467: "Specificare la patologia",
    468: "Infezioni acute delle vie respiratorie",
    469: "Infezioni acute delle vie respiratorie superiori",
    470: "Altre malattie delle vie respiratorie superiori",
    471: "Laringite e tracheite acuta",
    472: "Polmonite e influenza",
    473: "Tonsillite acuta",
    474: "Malattie polmonari croniche ostruttive e condizioni associate",
    475: "Faringite acuta",
    476: "Pneumoconiosi e altre malattie del polmone da agenti esterni",
    477: "Sinusite acuta",
    478: "Altre malattie del sistema respiratorio",
    479: "Rinofaringite acuta (raffreddore comune)",
    480: "Bronchite e bronchiolite acuta",
    481: "Laringite e laringotracheite cronica",
    482: "Rinite allergica",
    483: "Polipo nasale",
    484: "Faringite e rinofaringite cronica",
    485: "Sinusite cronica",
    486: "Malattie croniche delle tonsille e delle adenoidi",
    487: "Bronchite cronica",
    488: "Enfisema",
    489: "Asma",
    490: "Bronchiectasie",
    491: "Alveolite allergica estrinseca",
    492: "Altro",
    493: "Malattie del globo oculare",
    494: "Distacco e rotture della retina",
    495: "Altre malattie della retina",
    496: "Cataratta",
    497: "Glaucoma",
    498: "Vizi di rifrazione e disturbi dell'accomodazione",
    499: "Cecità e ipovisione",
    500: "Disturbi visivi",
    501: "Cheratite",
    502: "Affezioni dell'iride e del corpo ciliare",
    503: "Opacità corneali e altre alterazioni della cornea",
    504: "Infiammazioni corioretiniche e cicatrici della coroide",
    505: "Malattie della congiuntiva",
    506: "Infiammazione delle palpebre",
    507: "Altre affezioni delle palpebre",
    508: "Affezioni dell'apparato lacrimale",
    509: "Condizioni patologiche dell'orbita",
    510: "Malattie del nervo e delle vie ottiche",
    511: "Strabismo ed altri disturbi dei movimenti binoculari",
    512: "Altre malattie dell'occhio",
    513: "Disturbi dell'orecchio esterno",
    514: "Otite media non suppurativa",
    515: "Otite media suppurativa e non specificata",
    516: "Mastoidite e condizioni morbose correlate",
    517: "Altri disturbi della membrana timpanica",
    518: "Altri disturbi dell'orecchio medio e della mastoide",
    519: "Sindromi vertiginose ed altri disturbi del sistema vestibolare",
    520: "Otosclerosi",
    521: "Altri disturbi dell'orecchio",
    522: "Perdita dell'udito",
    523: "Altro",
}

# ──────────────────────────────────────────────────────
# 13 Aree Terapeutiche Canoniche (classificazione ATC)
# ──────────────────────────────────────────────────────
AREE_CANONICHE: list[str] = [
    "Apparato gastrointestinale e metabolismo",
    "Sangue e organi emopoietici",
    "Sistema cardiovascolare",
    "Dermatologici",
    "Sistema genito-urinario e ormoni sessuali",
    "Preparati ormonali sistemici, esclusi ormoni sessuali",
    "Antimicrobici per uso sistemico",
    "Farmaci antineoplastici e immunomodulatori",
    "Sistema muscolo-scheletrico",
    "Sistema nervoso centrale",
    "Antiparassitari",
    "Sistema respiratorio",
    "Organi di senso",
]

# ──────────────────────────────────────────────────────
# Mappa completa: valore raw Q7a → area canonica ATC
# Copertura: tutti gli 85 valori osservati nel dataset
# ──────────────────────────────────────────────────────
_GI   = "Apparato gastrointestinale e metabolismo"
_SAN  = "Sangue e organi emopoietici"
_CARD = "Sistema cardiovascolare"
_DERM = "Dermatologici"
_GU   = "Sistema genito-urinario e ormoni sessuali"
_ORM  = "Preparati ormonali sistemici, esclusi ormoni sessuali"
_ANTI = "Antimicrobici per uso sistemico"
_ONCO = "Farmaci antineoplastici e immunomodulatori"
_MUSC = "Sistema muscolo-scheletrico"
_SNC  = "Sistema nervoso centrale"
_PARA = "Antiparassitari"
_RESP = "Sistema respiratorio"
_SENS = "Organi di senso"

Q7A_CANONICAL: dict[str, str] = {
    # ── Apparato gastrointestinale e metabolismo ──────────────
    "Apparato gastrointestinale e metabolismo":         _GI,
    "Apparato gastro intestinale e metabolico":         _GI,
    "IBS":                                              _GI,
    "MORBO DI CHRON":                                   _GI,
    "CELIACHIA":                                        _GI,
    "REFLUSSO GASTROESOFAGE":                           _GI,
    "COLITE ULCEROSA":                                  _GI,
    "GASTRITE":                                         _GI,
    "GASTRITE DUODENALE":                               _GI,
    "EMORROIDI":                                        _GI,
    "polipi colici":                                    _GI,
    "STIPSI":                                           _GI,
    "ULCERA GASTRICA":                                  _GI,
    "IBD":                                              _GI,

    # ── Sangue e organi emopoietici ───────────────────────────
    "Sangue e organi emopoietici":                      _SAN,
    " Malattia di Pompe ":                              _SAN,

    # ── Sistema cardiovascolare ───────────────────────────────
    "Sistema cardiovascolare":                          _CARD,
    "ICTUS":                                            _CARD,

    # ── Dermatologici ─────────────────────────────────────────
    "Dermatologici":                                    _DERM,
    "dermatite atopica":                                _DERM,
    "dertite atopica":                                  _DERM,   # typo
    "acne":                                             _DERM,
    "acne ":                                            _DERM,   # trailing space
    "psoriasi":                                         _DERM,
    "psoriasi lieve":                                   _DERM,
    "psoriasi severa":                                  _DERM,
    "psoriasi moerata severa":                          _DERM,
    "psoriasi guttuta":                                 _DERM,
    "dermatiti funginee":                               _DERM,
    "cheratosi attinica":                               _DERM,
    "basilioma":                                        _DERM,
    "alopecia":                                         _DERM,
    "pelle secca":                                      _DERM,
    "allergie cutanee":                                 _DERM,
    "eczema":                                           _DERM,
    "dermatiti":                                        _DERM,
    "verruche":                                         _DERM,
    "vitiligine":                                       _DERM,
    "irritazioni cutanee":                              _DERM,
    "linfoma cutaneo":                                  _DERM,   # skin lymphoma

    # ── Sistema genito-urinario e ormoni sessuali ─────────────
    "Sistema genito-urinario e ormoni sessuali":        _GU,
    "ENDOMETRIOSI":                                     _GU,
    "DISFUNZIONE ERETTILE":                             _GU,
    "CONTRACCEZIONE":                                   _GU,
    "CISTITI":                                          _GU,
    "FERTILITA'":                                       _GU,
    "FIBROMI UTERINI":                                  _GU,

    # ── Preparati ormonali sistemici, esclusi ormoni sessuali ─
    "Preparati ormonali sistemici, esclusi ormoni sessuali": _ORM,
    "MENOPAUSA":                                        _ORM,
    "VAMPATE":                                          _ORM,
    "IPOTIROIDISMO":                                    _ORM,

    # ── Antimicrobici per uso sistemico ──────────────────────
    "Antimicrobici per uso sistemico":                  _ANTI,
    "INFEZIONI BATTERICHE":                             _ANTI,
    "INFEZIONI MICOTICHE":                              _ANTI,
    "INFEZIONI FUNGINEE":                               _ANTI,

    # ── Farmaci antineoplastici e immunomodulatori ────────────
    "Farmaci antineoplastici e immunomodulatori":       _ONCO,
    "melanoma":                                         _ONCO,
    "melanomi":                                         _ONCO,

    # ── Sistema muscolo-scheletrico ───────────────────────────
    "Sistema muscolo-scheletrico":                      _MUSC,
    "STENOSI SPINALE":                                  _MUSC,

    # ── Sistema nervoso centrale ──────────────────────────────
    "Sistema nervoso centrale":                         _SNC,
    "EPILESSIA":                                        _SNC,
    "epilessia":                                        _SNC,
    "PARKINSON":                                        _SNC,
    "Alzheimer":                                        _SNC,
    "DEPRESSIONE":                                      _SNC,
    "slcerosi multipla":                                _SNC,   # typo
    "SCLEROSI MULTIPLA":                                _SNC,
    "malattie neurodegenerative":                       _SNC,
    "disturbi psicotici":                               _SNC,
    "disturbi dell'umore":                              _SNC,
    "NARCOLESSIA":                                      _SNC,
    "insonnia":                                         _SNC,
    "NEUROPATIE PERIFERICHE":                           _SNC,
    "Dolore neuropatico":                               _SNC,
    "CONVULSIONI":                                      _SNC,
    "CEFALEE TENSIVE":                                  _SNC,
    "SLA":                                              _SNC,
    "emicrania":                                        _SNC,
    "Corea di Huntington":                              _SNC,

    # ── Antiparassitari ───────────────────────────────────────
    "Antiparassitari":                                  _PARA,

    # ── Sistema respiratorio ──────────────────────────────────
    "Sistema respiratorio":                             _RESP,

    # ── Organi di senso ───────────────────────────────────────
    "Organi di senso":                                  _SENS,
    "VERTIGINI":                                        _SENS,   # vestibolare
}


def normalizza_q7a(val) -> str | None:
    """
    Mappa un valore raw Q7a a una delle 13 aree canoniche ATC.
    Valori non mappati (es. 'altro', valori rari) → None (esclusi dal filtro).
    """
    if val is None:
        return None
    import pandas as pd
    if isinstance(val, float) and pd.isna(val):
        return None
    s = str(val).strip()
    if not s:
        return None
    return Q7A_CANONICAL.get(s)   # None se non mappato → escluso dal filtro


def normalizza_q7b(val) -> str | None:
    """
    Converte un valore Q7b in label leggibile:
    - Numerico (int o str convertibile) → lookup in CODICI_PATOLOGIE
    - Stringa → strip() + title()
    - NaN/None → None
    """
    import pandas as pd
    if val is None:
        return None
    if isinstance(val, float):
        if pd.isna(val):
            return None
        try:
            code = int(val)
            return CODICI_PATOLOGIE.get(code, str(int(val)))
        except (ValueError, OverflowError):
            return None
    if isinstance(val, int):
        return CODICI_PATOLOGIE.get(val, str(val))
    # String
    s = str(val).strip()
    if not s or s.lower() in ("nan", "none", ""):
        return None
    # Prova a convertire a int (es. "63")
    try:
        code = int(float(s))
        return CODICI_PATOLOGIE.get(code, s.title())
    except (ValueError, TypeError):
        pass
    # Abbreviazioni (es. BPCO, IBD, IBS, HIV): <= 10 char tutto maiuscolo → lascia invariato
    if s == s.upper() and len(s) <= 10 and " " not in s:
        return s
    # Testo misto o lungo → title case
    return s.title()
